on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: covr-pr

jobs:
  test-coverage:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_KEEP_PKG_SOURCE: yes
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      SLACK_SKIPLOAD: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      SLACK_API_TEST_MODE: false
      SLACKVERSE_TEST_RATE: true

    steps:
      - uses: actions/checkout@main

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage

      - name: Test coverage
        run: covr::package_coverage()
        shell: Rscript {0}
