on:
  push:
    branches: [main, master]
  workflow_dispatch:

name: covr-main

jobs:
  test-coverage:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}

    env:
      R_KEEP_PKG_SOURCE: yes
      SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
      SLACK_SKIPLOAD: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SLACK_API_TEST_MODE: true

    steps:
      - uses: actions/checkout@main

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

      - name: covrpage
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pak::pkg_install("hadley/emo")' \
                  -e 'pak::pkg_install("yonicd/covrpage@actions")' \
                  -e 'covrpage::covrpage_ci()'
          git commit tests/README.md -m 'Update tests/README.md' || echo "No changes to commit"
          git commit README.Rmd -m 'Update README.Rmd' || echo "No changes to commit"
          git commit README.md -m 'Update README.md' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
